# Generated by Django 3.1 on 2020-08-25 13:06

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200825_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='owed_by',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='user',
            name='owes',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
